--TASK 1 MOVIES

--1
Select m.TITLE,me.NAME from movie as m
JOIN MOVIEEXEC as me
ON me.CERT# = m.PRODUCERC#
WHERE m.PRODUCERC# = (SELECT me.CERT# FROM MOVIEEXEC as me
JOIN MOVIE as m
ON me.CERT# = m.PRODUCERC#
WHERE m.TITLE = 'Star wars')

--2
Select DISTINCT me.name  from STARSIN as s
JOIN MOVIE as m
ON s.MOVIETITLE = m.TITLE
JOIN MOVIEEXEC as me
ON m.PRODUCERC# = me.CERT#
WHERE s.STARNAME = 'Harrison Ford'

--3
SELECT DISTINCT s.NAME,si.STARNAME FROM STUDIO as s
JOIN MOVIE as m
ON s.NAME = m.STUDIONAME
JOIN STARSIN as si
ON m.TITLE = si.MOVIETITLE
ORDER BY s.NAME

--4
SELECT s.STARNAME,me.NETWORTH,m.TITLE from MOVIEEXEC as me
JOIN MOVIE as m
ON m.PRODUCERC# = me.CERT#
JOIN STARSIN as s
ON s.MOVIETITLE = m.TITLE
WHERE me.NETWORTH = (Select MAX(NETWORTH) from MOVIEEXEC);

--5
SELECT ms.NAME,s.MOVIETITLE FROM MOVIESTAR as ms
LEFT JOIN STARSIN as s
ON ms.NAME = s.STARNAME
WHERE  s.MOVIETITLE IS NULL;

--6
SELECT s.STARNAME as [name] FROM STARSIN as s
JOIN MOVIESTAR as ms
ON s.STARNAME = ms.NAME
WHERE S.MOVIETITLE = 'The Usual Suspects' and ms.GENDER = 'M';

--7
SELECT s.STARNAME  FROM MOVIE as m
JOIN STARSIN as s 
ON m.TITLE = s.MOVIETITLE
WHERE m.[YEAR] = 1995 AND m.STUDIONAME = 'MGM';

--8
SELECT DISTINCT me.NAME FROM STUDIO as s
JOIN MOVIE as m
ON m.STUDIONAME = s.NAME
JOIN MOVIEEXEC as me
ON me.CERT# = m.PRODUCERC#
WHERE s.NAME = 'MGM';

--9
SELECT m.TITLE FROM MOVIE as m
WHERE m.LENGTH > (SELECT m.[LENGTH] FROM MOVIE as m
WHERE m.TITLE='Star wars');

--10
SELECT me.NAME FROM MOVIEEXEC as me
WHERE me.NETWORTH > (SELECT me.NETWORTH from MOVIEEXEC as me
                    WHERE me.NAME = 'Stephen Spielberg');

--11
SELECT m.TITLE FROM MOVIE as m
JOIN MOVIEEXEC as me
ON me.CERT# = m.PRODUCERC#
WHERE me.NAME IN (SELECT me.NAME FROM MOVIEEXEC as me
WHERE me.NETWORTH > (SELECT me.NETWORTH from MOVIEEXEC as me
                    WHERE me.NAME = 'Stephen Spielberg'));


